version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server  # Path to your Eureka server application
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  leave-service:
    build:
      context: ./work-hours  # Path to your Leave application
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  api-gateway:
    build:
      context: ./api-gateway  # Path to your API Gateway application
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - leave-service

